workspaces: [Óà∂Ô∏Å êå∞:term, Ôâ© êå±:web, Óâß êå≤:dev, ÔÖú êå≥:doc, ÔÄæ êå¥:draw, ﬂ∑ êåµ:gfx, ‚úΩ êå∂:obs, ÔÄæ êå∑:pic, ÔÜ∑ êå∏:games, ÔÇ≠ êåπ:sys, Ôáç êå∫:vm, Ôáã êåª:wine]

default: !!python/object/new:negwm.lib.keymap.bindmap
  listitems:
  - !!python/object/new:negwm.lib.keymap.keymap
    dictitems: {Mod4+4: ~/bin/screenshot, Mod4+Control+4: ~/bin/screenshot -r, Mod4+Shift+4: /usr/bin/flameshot gui}
    state: {exit: false, fmt: 'exec {cmd}'}
  - !!python/object/new:negwm.lib.keymap.keymap
    dictitems: {
      Mod1+grave: ~/bin/rofi-run,
      Mod4+8: ~/bin/pl vol mute,
      Mod4+Return: /usr/bin/i3-sensible-terminal, 
      Mod4+Shift+8: ~/bin/pl vol unmute,
      Mod4+Shift+9: /usr/bin/dunstctl history-pop,
      Mod4+Shift+l: ~/bin/rofi-lutris, 
      Mod4+Shift+m: ~/bin/main-menu, 
      Mod4+Shift+x: sh -c "~/bin/game start && ~/bin/game end",
      Mod4+c: ~/bin/clip, 
      Mod4+m: /bin/zsh -c "~/bin/music-rename current",
      Mod4+p: /usr/bin/rofi-pass,
      Mod4+space: /usr/bin/dunstctl close-all,
      XF86Sleep: /usr/bin/systemctl suspend
    }
    state: {exit: false, fmt: 'exec --no-startup-id {cmd}'}
  - !!python/object/new:negwm.lib.keymap.keymap
    dictitems: {Mod4+7: child, Mod4+h: left, Mod4+j: down, Mod4+k: up, Mod4+l: right}
    state: {exit: false, fmt: 'focus {cmd}'}
  - !!python/object/new:negwm.lib.keymap.keymap
    dictitems: {Mod1+Control+a: parent, Mod1+Control+c: child}
    state: {exit: false, fmt: 'focus {cmd}'}
  - !!python/object/new:negwm.lib.keymap.keymap
    dictitems: {Mod4+Shift+bracketleft: left, Mod4+Shift+bracketright: right}
    state: {exit: false, fmt: 'move workspace to output {cmd}'}
  - !!python/object/new:negwm.lib.keymap.keymap
    dictitems: {Mod4+Shift+apostrophe: restart, Mod4+apostrophe: reload; exec --no-startup-id systemctl --user restart negwm, Mod4+backslash: reload;
        exec --no-startup-id systemctl --user restart negwm; exec --no-startup-id polybar-msg cmd restart}
    state: {exit: false, fmt: ''}
  - !!python/object/new:negwm.lib.keymap.keymap
    dictitems: {Mod1+Tab: switch, Mod4+Shift+grave: focus_prev_visible, Mod4+grave: focus_next_visible, Mod4+slash: switch}
    state: {exit: false, fmt: '$lastgo {cmd}'}
  - !!python/object/new:negwm.lib.keymap.keymap
    dictitems: {Mod4+3: next, Mod4+Control+a: dialog, Mod4+Control+s: geom_dump, Mod4+Control+space: geom_restore, Mod4+s: hide_current}
    state: {exit: false, fmt: '$scratchpad {cmd}'}
  - !!python/object/new:negwm.lib.keymap.keymap
    dictitems: {Mod4+Shift+2: cmd play-pause, Mod4+comma: cmd previous, Mod4+period: cmd next, XF86AudioLowerVolume: vol down, XF86AudioRaiseVolume: vol up}
    state: {exit: false, fmt: 'exec --no-startup-id ~/bin/pl {cmd}'}
  - !!python/object/new:negwm.lib.keymap.keymap
    dictitems: {XF86AudioNext: next, XF86AudioPlay: play, XF86AudioPrev: previous, XF86AudioStop: stop}
    state: {exit: false, fmt: 'exec --no-startup-id ~/bin/pl cmd {cmd}'}
  - !!python/object/new:negwm.lib.keymap.keymap
    dictitems: {Mod1+Control+g: $menu/winact ws, Mod1+g: $menu/winact win, Mod4+Control+grave: $menu/i3menu, Mod4+Shift+a: $menu/winact attach,
      Mod4+Shift+d: $menu/props del, Mod4+Shift+s: $menu/props}
    state: {exit: false, fmt: ''}
  - !!python/object/new:negwm.lib.keymap.keymap
    dictitems: {Mod1+Control+e: layout toggle split, Mod1+Control+r: layout tabbed, Mod1+Control+s: layout stacking, Mod1+Control+t: layout tabbed,
      Mod4+Escape: kill, Mod4+q: fullscreen toggle, Mod4+y: sticky toggle}
    state: {exit: false, fmt: ''}
  state: {bind: '', name: '', pretty_name: ''}

resize: !!python/object/new:negwm.lib.keymap.bindmap
  listitems:
  - !!python/object/new:negwm.lib.keymap.keymap
    dictitems:
      bottom: [j, s]
      left: [h, a]
      right: [l, d]
      top: [k, w]
    state: {exit: false, fmt: '$actions resize {cmd} 20'}
  - !!python/object/new:negwm.lib.keymap.keymap
    dictitems:
      bottom: [Shift+j, Shift+s]
      left: [Shift+h, Shift+a]
      right: [Shift+l, Shift+d]
      top: [Shift+k, Shift+w]
    state: {exit: false, fmt: '$actions resize {cmd} -4'}
  state: {bind: Mod4+r, name: '%{T4}Ôê§%{T-}', pretty_name: ''}

spec: !!python/object/new:negwm.lib.keymap.bindmap
  listitems:
  - !!python/object/new:negwm.lib.keymap.keymap
    dictitems: {Shift+d: floating toggle, Shift+i: $menu/xsettings icon, Shift+t: $menu/xsettings gtk, e: '[urgent=latest] focus', i: $menu/audio
        input, l: exec ~/bin/x11lock, m: $menu/xprop, o: $menu/audio output}
    state: {exit: true, fmt: ''}
  state: {bind: Mod1+e, name: '%{T4}ÔÜ≤%{T-}', pretty_name: ''}

wallpaper: !!python/object/new:negwm.lib.keymap.bindmap
  listitems:
  - !!python/object/new:negwm.lib.keymap.keymap
    dictitems: {'6': ~/bin/wl, Mod4+Shift+6: ~/bin/wl, Shift+6: ~/bin/wl, m: ~/bin/wl-convert mono, n: ~/bin/wl-convert normal, r: ~/bin/wl-convert
        retro}
    state: {exit: false, fmt: 'exec --no-startup-id {cmd}'}
  - !!python/object/new:negwm.lib.keymap.keymap
    dictitems:
      '': [Space, q]
    state: {exit: true, fmt: ''}
  state: {bind: Mod4+Shift+6, name: '%{T4}ÔÄæ%{T-}', pretty_name: ''}

wm: !!python/object/new:negwm.lib.keymap.bindmap
  listitems:
  - !!python/object/new:negwm.lib.keymap.keymap
    dictitems: {backslash: splitv, grave: default, minus: splith, t: tabbed}
    state: {exit: true, fmt: 'layout {cmd}'}
  - !!python/object/new:negwm.lib.keymap.keymap
    dictitems: {Tab: toggle}
    state: {exit: false, fmt: 'layout {cmd}'}
  - !!python/object/new:negwm.lib.keymap.keymap
    dictitems:
      horizontal: [Shift+h, Shift+l]
      vertical: [Shift+j, Shift+k]
    state: {exit: true, fmt: split}
  - !!python/object/new:negwm.lib.keymap.keymap
    dictitems: {a: left, d: right, s: down, w: up}
    state: {exit: false, fmt: 'move {cmd}'}
  - !!python/object/new:negwm.lib.keymap.keymap
    dictitems: {Shift+a: hup, Shift+d: vright, Shift+s: vleft, Shift+w: hdown}
    state: {exit: false, fmt: '$actions x2 {cmd}'}
  - !!python/object/new:negwm.lib.keymap.keymap
    dictitems:
      Shift+c: resize
      Shift+plus: grow
      c: none
      m: maximize
      revert_maximize: [Shift+m, Shift+x, Shift+y]
      shrink: [Shift+minus]
      x: maxhor
      y: maxvert
    state: {exit: false, fmt: $actions}
  state: {bind: Mod4+minus, name: '%{T4}ÔÄâ%{T-}', pretty_name: ''}
